version: '3.9'

services:
  db:
    image: postgres
    container_name: django-vue-db
    environment:
      POSTGRES_USER: my_user 
      POSTGRES_PASSWORD: MySuperPassword
      POSTGRES_DB: EmpleadosDB
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: docker/DockerFileBackEnd      
    container_name: django-vue-backend  
    command: ./docker/backend_setup.sh
    environment:
      POSTGRES_NAME: EmpleadosDB
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: MySuperPassword
      POSTGRES_HOST: db
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
  vue:
    build:
      context: .
      dockerfile: docker/DockerFileFrontEnd 
    container_name: django-vue-frontend
    command: ./docker/frontend_setup.sh
    volumes:
      - .:/app
    ports:
      - "8082:8080"
    depends_on:
      - django