# Generated by Django 4.1 on 2022-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('DepartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentoNombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('EmpleadoId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpleadoNombre', models.CharField(max_length=256)),
                ('Departamento', models.CharField(max_length=256)),
                ('FechaIngreso', models.DateField()),
                ('FotoEmpleado', models.CharField(max_length=500)),
            ],
        ),
    ]
