# Generated by Django 4.1 on 2022-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_sueldo_alter_empleado_fotoempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='FotoEmpleado',
            field=models.CharField(max_length=256),
        ),
    ]
