# Generated by Django 4.1 on 2022-08-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_alter_empleado_fotoempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sueldo',
            name='SueldoId',
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='Empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Empleados.empleado'),
        ),
    ]
