# Generated by Django 4.1 on 2022-08-15 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_remove_sueldo_sueldoid_alter_sueldo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldo',
            name='Bonificaciones',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='Descuentos',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='SueldoBase',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='sueldo',
            name='SueldoLiquido',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
